version: '3.8'

services:
  order-service:
    image: pos-order-service:latest
    container_name: pos-order-service
    ports:
      - '8081:8081'
    networks:
      - pos-network

  inventory-service:
    image: pos-inventory-service:latest
    container_name: pos-inventory-service
    ports:
      - '8082:8082'
    networks:
      - pos-network

  api-gateway:
    image: pos-api-gateway:latest
    container_name: pos-api-gateway
    ports:
      - '8080:8080'
    depends_on:
      - order-service
      - inventory-service
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge
